# Site settings
title: Brian Honohan
description: > 
  Personal site of Brian Honohan, a Philadelphia based data engineer.
baseurl: ""
twitter_username: brianhonohan
github_username:  brianhonohan
flickr_username:  brian-honohan

# Build settings
markdown: kramdown
